apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-gycg
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0027-tenant/tkrw-pr712-0075-0027-app/devfile-sample-gycg@sha256:5c8c90d72bb9610827ab4bc2ddd676652244e81a76b09467456f7693842a7e54
        name: my-nodejs
        resources: {}
status: {}
